### ISSUE TITLE
Inaccurate figures 

### ISSUE THREAD

**Issue by rbasamoyai** [MTN73/IB-conversion-calculator#1]
Outdated, L, inflated mark conversions

Source:
![image](https://github.com/MTN73/IB-conversion-calculator/assets/86567158/2cb66282-931b-4375-bf0f-861f04f1c5c0)

**Comment by JasonEl1** [comment]
These are in fact the May 2022 grade boundaries. I wasn't able to find the 2023 ones but if you can find them (TZ1!) I would appreciate a link or pr 👍

**Comment by JasonEl1** [comment]
Updated to use May 2023

**Comment by rbasamoyai** [comment]
the goat
